name: Vercel Deployemnt

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  schedule:
    - cron: '* * */10 * *'

jobs:
  Refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install

      - uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: refresh-dates

      - name: Commit and push if changed
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update data.json'
          add: 'src/data.json'

  Deploy-Production:
    needs: [Refresh]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
